### ISSUE TITLE
Continuously import logs of GCP services

### ISSUE THREAD

**Issue by steren** [apex/roadmap#47]
I want to use Apex Logs as a Log viewer for the logs of many of my GCP services.

However, I am hesitant instrumenting my code to use the dedicated Apex Logs client libraries, notably because some logs are not logged by my code (e.g. request logs of my Cloud Run service). 

I wish Apex Logs had a way to continuously import logs of GCP services. I would grant Apex Logs the IAM permission to read logs, and it would fetch them automatically. Or alternatively, I would configure a [log export](https://cloud.google.com/logging/docs/export) with PubSub pushing to Apex Logs.

**Comment by tj** [comment]
Agreed! The export stuff looks good I'll have to look into that, added it to #36 just keeping those all in one spot for now but it might be better to split them later
